#
# Copyright (c) 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- block:
  - name: "Set swappiness to {{swappiness}} in /etc/sysctl.conf"
    become: yes
    become_user: root
    sysctl:
      name: vm.swappiness
      value: "{{swappiness}}"
      state: present
      sysctl_set: yes
  tags:
    - swappiness_config
