####################################################################
#### viya-dbct.yml                                              ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
#
# Copyright (c) 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
- name: SAS Infrastructure Data Server Consul Template - {{dbname}}
  script: "viya-svs.sh {{dbaction}} {{dbname}} {{dbtype}}"
  when: not ansible_check_mode
