config:
    application:
        sas.identities.providers.ldap.connection:
            host: 'your_ad_hostname'
            password: 'dummypass'
            port: '389'
            url: 'ldap://${sas.identities.providers.ldap.connection.host}:${sas.identities.providers.ldap.connection.port}'
            anonymousBind: 'false'
            userDN: 'CN=[test] SAS Demo Account,OU=Generic Accounts,OU=Admin,DC=na,DC=customer,DC=com'
        sas.identities.providers.ldap.group:
            baseDN: 'OU=Groups,DC=na,DC=customer,DC=com'
        sas.identities.providers.ldap.user:
            baseDN: 'dc=customer,dc=com'
            searchFilter: 'sAMAccountName={0}'
        sas.identities:
            administrator: 'your_user_id'